# Generated by Django 5.1.1 on 2024-10-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_news_paragraph_alter_service_paragraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trianing',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('pointsData', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
