# Generated by Django 5.1.1 on 2024-10-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_trianing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.AlterField(
            model_name='news',
            name='paragraph',
            field=models.CharField(max_length=3500),
        ),
        migrations.AlterField(
            model_name='service',
            name='paragraph',
            field=models.TextField(max_length=3500, null=True),
        ),
    ]
